### ISSUE TITLE
Contact method

### ISSUE THREAD

**Issue by Michael21107** [Fern-Aerell/RagdollPlayerWhenShot#1]
Hey, I just wanted to let you know that your 5mods profile (which essentially "promotes" this repo) has an invalid Discord invite link.

**Comment by fernaerell** [comment]
Thank you for letting me know about this. I will delete it because my Discord server is under development.

**Comment by Michael21107** [comment]
No problem, could you please tell me your discord username or write to me (michael21107)?

**Comment by fernaerell** [comment]
> No problem, could you please tell me your discord username or write to me (michael21107)?

Yes, my discord username is 4erel.
